= Chart Data

This repository contains the authoritative data of the Chronostratigraphic Chart produced by the International Commission on Stratigraphy, distributed online at https://stratigraphy.org/chart.

This data is in the form of a https://en.wikipedia.org/wiki/Knowledge_graph[Knowledge Graph] formulated according to https://en.wikipedia.org/wiki/Semantic_Web[Semantic Web] principles, which means it's serialized in https://en.wikipedia.org/wiki/Resource_Description_Framework[RDF] and, after loading, can be queried using the https://en.wikipedia.org/wiki/SPARQL[SPARQL query language].

The Chart is formulated as a https://www.w3.org/TR/skos-primer/[SKOS Vocabulary] with many additional properties relevant to timescales and geology.

This data form of the Chart will soon be used to produce all PDF and other visual forms of the Chart.


== Creating a Release

To publish a release, go to the GitHub releases page and create a new release. This release should be set to create a new tag using SemVer preceded by `v`, but the major and minor versions should reflect the stratigraphic versions, for example `v2023.09.1`.

Creating this tag will trigger a workflow that generates the PDFs and publishes them to the release.


== Copyright & License

This data is copyrighted as follows:

&copy; International Commission on Stratigraphy, 2024

This data is licensed for use with the Creative Commons Attribution 4.0 license:

* <https://creativecommons.org/licenses/by/4.0/>

A local copy of the license deed is stored in the file LICENSE in this repository.


== Contact

Please contact the executive of the International Commission on Stratigraphy with all questions via https://stratigraphy.org/executive

You may also log any issues with the data at https://github.com/i-c-stratigraphy/chart/issues.


== Development

Make UI changes in `chart-ui/`.

Install dependencies and run the UI locally from that directory:

[source,bash]
----
cd chart-ui
pnpm install
pnpm run dev
----

The development server runs at http://localhost:3000.

Visual changes affect the generated PDFs, so any layout, typography, spacing, or other presentation change should be tested locally by running:

[source,bash]
----
task test-pdfs
----

This runs the local PDF generation workflow and prints the path to the generated `chart-pdf.zip` artifact so it can be inspected before opening a PR or cutting a release.
