# https://taskfile.dev

version: '3'

tasks:

  test-pdfs:
    desc: Run build + publish-pdfs jobs locally to validate PDF generation
    cmds:
      - gh act release -W .github/workflows/deploy-chart.yml -j publish-pdfs --artifact-server-path /tmp/github-artifacts --artifact-server-port 34568 --action-cache-path /tmp/act-cache
